version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "npm"
    directory: "/firebase/functions"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
      jest:
        patterns:
          - "@swc/jest"
          - "@types/jest"
          - "jest"

  - package-ecosystem: "pub"
    directory: "/packages/core"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      firebase:
        patterns:
          - "firebase_*"
          - "cloud_firestore"
          - "cloud_functions"
      freezed:
        patterns:
          - "freezed_annotation"
          - "freezed"
          - "json_annotation"
          - "json_serializable"
      riverpod:
        patterns:
          - "hooks_riverpod"
          - "riverpod_*"
      go_router:
        patterns:
          - "go_router"
          - "go_router_builder"
      slang:
        patterns:
          - "slang"
          - "slang_*"
      info_plus:
        patterns:
          - "*_info_plus"

  - package-ecosystem: "pub"
    directory: "/packages/listen_to_music_by_location"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      firebase:
        patterns:
          - "firebase_*"
          - "cloud_firestore"
          - "cloud_functions"
      freezed:
        patterns:
          - "freezed_annotation"
          - "freezed"
          - "json_annotation"
          - "json_serializable"
      riverpod:
        patterns:
          - "hooks_riverpod"
          - "riverpod_*"
      go_router:
        patterns:
          - "go_router"
          - "go_router_builder"
      slang:
        patterns:
          - "slang"
          - "slang_*"
      info_plus:
        patterns:
          - "*_info_plus"
