name: garage

packages:
  - packages/*

repository: https://github.com/KoheiKanagu/garage

command:
  version:
    branch: main
    linkToCommits: true
  bootstrap:
    runPubGetInParallel: false
    hooks:
      post: |
        melos run pub:get

scripts:
  analyze:
    run: |
      fvm flutter pub get
      fvm flutter pub run build_runner build --delete-conflicting-outputs
      (cd MELOS_ROOT_PATH && grind update-coverage-test --package=MELOS_PACKAGE_NAME)
      fvm dart fix --apply lib
      fvm dart format --set-exit-if-changed .
      fvm dart analyze --fatal-infos .
      fvm dart run custom_lint
      git diff --exit-code
    exec:
      concurrency: 1
      orderDependents: true

  pub:get:
    run: |
      fvm dart pub get
      melos exec -- "fvm flutter pub get"

  flutter:test:
    exec: |
      fvm flutter pub get
      fvm flutter test \
        --exclude-tags golden \
        --flavor dev
    packageFilters:
      flutter: true
      dirExists: test

  flutter:golden:test:
    exec: |
      fvm flutter pub get

      fvm flutter test \
        --tags golden \
        --flavor dev
    packageFilters:
      flutter: true
      dirExists: test

  flutter:golden:update:
    exec: |
      fvm flutter pub get

      fvm flutter test \
        --update-goldens \
        --tags golden \
        --flavor dev
    packageFilters:
      flutter: true
      dirExists: test
      dependsOn: alchemist

  build_runner:build:
    run: |
      fvm flutter pub get
      fvm flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      dependsOn: build_runner

  build_runner:watch:
    exec: |
      fvm flutter pub get
      fvm flutter pub run build_runner watch --delete-conflicting-outputs
    packageFilters:
      flutter: true
      dependsOn: build_runner

  pod:update:
    run: |
      fvm flutter pub get

      cd ios
      pod update
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:apk:dev:
    run: |
      fvm flutter build apk \
        --release \
        --flavor dev \
        --target-platform android-arm64 \
        --target lib/main_dev.dart \
        --obfuscate \
        --split-debug-info build/app/outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: android

  build:appbundle:prod:upload:
    run: |
      fvm flutter build appbundle \
        --release \
        --flavor prod \
        --target lib/main_prod.dart \
        --obfuscate \
        --split-debug-info build/app/outputs

      firebase crashlytics:symbols:upload \
        --app $(cat packages/$MELOS_PACKAGES/android/app/src/prod/google-services.json | jq -r '.client[0].client_info.mobilesdk_app_id') \
        build/app/outputs/app.android-*.symbols

      echo "TODO: upload app bundle to Google Play Console."
      # fastlane supply \
      #   --aab MELOS_PACKAGE_PATH/build/app/outputs/bundle/release/app-release.aab
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: android

  build:ios:no-codesign:dev:
    run: |
      fvm flutter build ios \
        --release \
        --no-codesign \
        --flavor dev \
        --target lib/main_dev.dart \
        --obfuscate \
        --split-debug-info build/app/outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:ios:no-codesign:prod:
    run: |
      fvm flutter build ios \
        --release \
        --no-codesign \
        --flavor prod \
        --target lib/main_prod.dart \
        --obfuscate \
        --split-debug-info build/app/outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:ipa:dev:
    run: |
      fvm flutter build ipa \
        --release \
        --flavor dev \
        --target lib/main_dev.dart \
        --export-options-plist configs/AdHocExportOptions.plist \
        --obfuscate \
        --split-debug-info build/app/outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:ipa:prod:upload:
    run: |
      fvm flutter build ipa \
        --release \
        --flavor prod \
        --target lib/main_prod.dart \
        --export-options-plist configs/AppStoreExportOptions.plist \
        --obfuscate \
        --split-debug-info build/app/outputs

      fastlane pilot upload \
        --ipa MELOS_PACKAGE_PATH/build/ios/ipa/*.ipa \
        --skip_waiting_for_build_processing
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  pigeon:
    exec: |
      fvm dart run pigeon \
        --input pigeons/message.dart
    packageFilters:
      dependsOn: pigeon

  clean:
    exec: |
      fvm flutter clean
    packageFilters:
      flutter: true
