name: garage

packages:
  - packages/*

repository: https://github.com/KoheiKanagu/garage

command:
  bootstrap:
    runPubGetInParallel: false
    hooks:
      post: |
        melos run pub:get

sdkPath: .fvm/versions/beta

scripts:
  check:
    description: |
      Run code generation, format, and static analysis.
      If any diff are found, it returns an error.
    run: |
      melos run generate && \
      melos run dart:fix:format && \
      git diff --exit-code && \
      melos run dart:analyze && \
      melos run dart:custom_lint

  dart:fix:format:
    description: |
      Run dart fix and format.
    run: |
      dart fix --apply tool
      melos exec -- dart fix --apply lib
      grind dart-format-all

  dart:analyze:
    description: |
      Run dart analyze.
    run: |
      dart analyze --fatal-infos .
      melos exec -- dart analyze --fatal-infos .

  dart:custom_lint:
    description: |
      Run custom lint.
    exec: |
      # rootのtoolディレクトリもcustom_lintかけたいが、対象のディレクトリを指定できないためできない
      dart run custom_lint

  pub:get:
    run: |
      dart pub get
      melos exec -- "flutter pub get"

  flutter:test:
    exec: |
      flutter test \
        --exclude-tags golden \
        --flavor dev
    packageFilters:
      flutter: true
      dirExists: test

  flutter:golden:test:
    description: |
      Run golden tests.
    exec: |
      flutter test \
        --tags golden \
        --flavor dev
    packageFilters:
      flutter: true
      dirExists: test

  flutter:golden:update:
    description: |
      Update golden tests.
    exec: |
      flutter test \
        --update-goldens \
        --tags golden \
        --flavor dev
    packageFilters:
      flutter: true
      dirExists: test

  build_runner:build:
    run: |
      dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      dependsOn: build_runner

  build_runner:watch:
    exec: |
      dart run build_runner watch --delete-conflicting-outputs
    packageFilters:
      flutter: true
      dependsOn: build_runner

  pod:install:
    run: |
      cd ios
      pod install
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  pod:update:
    run: |
      cd ios
      pod update
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:apk:dev:
    run: |
      flutter build apk \
        --release \
        --flavor dev \
        --target-platform android-arm64 \
        --target lib/main_dev.dart \
        --obfuscate \
        --split-debug-info build/app/outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: android

  build:appbundle:prod:upload:
    run: |
      flutter build appbundle \
        --release \
        --flavor prod \
        --target lib/main_prod.dart \
        --obfuscate \
        --split-debug-info build/app/outputs

      firebase crashlytics:symbols:upload \
        --app $(cat packages/$MELOS_PACKAGES/android/app/src/prod/google-services.json | jq -r '.client[0].client_info.mobilesdk_app_id') \
        build/app/outputs/app.android-*.symbols

      echo "TODO: upload app bundle to Google Play Console."
      # fastlane supply \
      #   --aab MELOS_PACKAGE_PATH/build/app/outputs/bundle/release/app-release.aab
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: android

  build:ios:config-only:
    run: |
      flutter build ios \
        --config-only \
        --flavor dev \
        --target lib/main_dev.dart
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:ios:no-codesign:dev:
    run: |
      flutter build ios \
        --release \
        --no-codesign \
        --flavor dev \
        --target lib/main_dev.dart \
        --obfuscate \
        --split-debug-info build/app/outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:ios:no-codesign:prod:
    run: |
      flutter build ios \
        --release \
        --no-codesign \
        --flavor prod \
        --target lib/main_prod.dart \
        --obfuscate \
        --split-debug-info build/app/outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:ipa:dev:
    run: |
      flutter build ipa \
        --release \
        --flavor dev \
        --target lib/main_dev.dart \
        --export-options-plist configs/AdHocExportOptions.plist \
        --obfuscate \
        --split-debug-info build/app/outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  build:ipa:prod:upload:
    run: |
      flutter build ipa \
        --release \
        --flavor prod \
        --target lib/main_prod.dart \
        --export-options-plist configs/AppStoreExportOptions.plist \
        --obfuscate \
        --split-debug-info build/app/outputs

      fastlane pilot upload \
        --ipa MELOS_PACKAGE_PATH/build/ios/ipa/*.ipa \
        --skip_waiting_for_build_processing
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: ios

  pigeon:
    exec: |
      dart run pigeon \
        --input pigeons/message.dart
    packageFilters:
      dependsOn: pigeon

  slang:
    exec: |
      dart run slang
    packageFilters:
      dependsOn: slang

  clean:
    exec: |
      flutter clean
    packageFilters:
      flutter: true

  generate:
    description: |
      Generate files.
    run: |
      grind update-si && \
      melos run build_runner:build --no-select && \
      melos run pigeon && \
      melos run slang && \
      grind update-coverage-test && \
      grind update-core-export && \
      grind dump-firestore-indexes
