name: garage_workspace

environment:
  sdk: ^3.3.0-0

dev_dependencies:
  collection: ^1.18.0
  custom_lint: ^0.5.7
  grinder: ^0.9.5
  melos: ^4.0.0
  riverpod_lint: ^2.3.7
  very_good_analysis: ^5.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
