name: garage_workspace

environment:
  sdk: ^3.4.0-0

dev_dependencies:
  collection: ^1.18.0
  custom_lint: ^0.6.0
  grinder: ^0.9.5
  intl: any
  markdown: ^7.2.1
  melos: ^4.1.0
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
