name: listen_to_music_by_location
publish_to: "none"

version: 0.0.2+15

environment:
  sdk: ^3.3.0-0
  flutter: ^3.18.0-0

dependencies:
  adaptive_dialog: ^2.0.0
  app_links: ^3.5.0
  budoux_dart: ^1.1.0
  cached_network_image: ^3.3.1
  clock: ^1.1.1
  cloud_firestore: ^4.15.0
  cloud_functions: ^4.6.1
  collection: ^1.18.0
  core:
    path: ../core
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.1
  feedback: ^3.0.0
  firebase_analytics: ^10.8.1
  firebase_app_check: ^0.2.1+9
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  firebase_crashlytics: ^3.4.10
  firebase_performance: ^0.9.3+9
  firebase_remote_config: ^4.3.9
  firebase_ui_auth: ^1.12.1
  firebase_ui_localizations: ^1.10.1
  firebase_ui_oauth_apple: ^1.2.17
  firebase_ui_oauth_google: ^1.2.17
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.0.0
  hooks_riverpod: ^2.4.9
  in_app_review: ^2.0.8
  intersperse: ^2.0.0
  intl: any
  jovial_svg: ^1.1.20
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  quick_actions: ^1.0.6
  riverpod_annotation: ^2.3.3
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  simple_logger: ^1.9.0+3
  slang: ^3.28.0
  slang_flutter: ^3.28.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.2
  uuid: ^4.3.1

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_gen_runner: ^5.3.2
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  pigeon: ^15.0.2
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  slang_build_runner: ^3.28.0
  test: any
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

  assets:
    - packages/budoux_dart/models/ja.json

    - assets/images/app_icon.webp

    - assets/images/how_to/step1_en.webp
    - assets/images/how_to/step1_ja.webp
    - assets/images/how_to/step2_en.webp
    - assets/images/how_to/step2_ja.webp
    - assets/images/how_to/step3_en.webp
    - assets/images/how_to/step3_ja.webp
    - assets/images/how_to/step4_en.webp
    - assets/images/how_to/step4_ja.webp
    - assets/images/how_to/step5_en.webp
    - assets/images/how_to/step5_ja.webp

    - assets/images/onboarding/screenshot_0.webp
    - assets/images/onboarding/screenshot_1.webp
    - assets/images/onboarding/screenshot_2.webp
    - assets/images/onboarding/screenshot_3.webp
    - assets/images/onboarding/screenshot_4.webp
    - assets/images/onboarding/screenshot_5.webp
    - assets/images/onboarding/screenshot_6.webp
    - assets/images/onboarding/screenshot_7.webp

    - assets/si/apple_music_icon.si
    - assets/si/apple_music_badge_ja.si
    - assets/si/apple_music_badge_en.si
# flutter_native_splash:
#   color: "#FAFDFD" # lightColorScheme.background
#   image: "assets/splash_icon.png"
#   color_dark: "#191C1D" # darkColorScheme.background
#   image_dark: "assets/splash_icon_dark.png"
#   android_12:
#     image: "assets/splash_icon.png"
#     color: "#FAFDFD" # lightColorScheme.background
#     image_dark: "assets/splash_icon_dark.png"
#     color_dark: "#191C1D" # darkColorScheme.background
#   android: true
#   ios: true
#   fullscreen: true
