name: listen_to_music_by_location
publish_to: "none"

version: 1.2.0

environment:
  sdk: 3.5.0-180.3.beta
  flutter: 3.23.0-0.1.pre

dependencies:
  adaptive_dialog: ^2.1.0
  app_links: ^6.1.4
  budoux_dart: ^1.2.0
  cached_network_image: ^3.4.0
  clock: ^1.1.1
  cloud_firestore: ^5.1.0
  cloud_functions: ^5.0.3
  collection: ^1.18.0
  core:
    path: ../core
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  feedback: ^3.1.0
  firebase_analytics: ^11.2.0
  firebase_app_check: ^0.3.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_performance: ^0.10.0+1
  firebase_remote_config: ^5.0.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.2.1
  google_mobile_ads: ^5.1.0
  hooks_riverpod: ^2.5.1
  in_app_review: ^2.0.9
  intersperse: ^2.0.0
  intl: any
  jovial_svg: ^1.1.21
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  quick_actions: ^1.0.7
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  smooth_page_indicator: ^1.2.0+3
  talker: ^4.3.4
  talker_flutter: ^4.3.4
  talker_riverpod_logger: ^4.4.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.6.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  pigeon: ^21.1.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  slang_build_runner: ^3.31.0
  test: any
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/budoux_dart/models/ja.json

    - assets/images/app_icon.webp

    - assets/images/how_to/step1_en.webp
    - assets/images/how_to/step1_ja.webp
    - assets/images/how_to/step2_en.webp
    - assets/images/how_to/step2_ja.webp
    - assets/images/how_to/step3_en.webp
    - assets/images/how_to/step3_ja.webp
    - assets/images/how_to/step4_en.webp
    - assets/images/how_to/step4_ja.webp
    - assets/images/how_to/step5_en.webp
    - assets/images/how_to/step5_ja.webp

    - assets/images/onboarding/screenshot_0.webp
    - assets/images/onboarding/screenshot_1.webp
    - assets/images/onboarding/screenshot_2.webp
    - assets/images/onboarding/screenshot_3.webp
    - assets/images/onboarding/screenshot_4.webp
    - assets/images/onboarding/screenshot_5.webp
    - assets/images/onboarding/screenshot_6.webp
    - assets/images/onboarding/screenshot_7.webp

    - assets/si/apple_music_icon.si
    - assets/si/apple_music_badge_ja.si
    - assets/si/apple_music_badge_en.si
flutter_native_splash:
  color: "#FB5C74"
  color_dark: "#FA233B"
  image: assets/images/app_icon_FB5C74.png
  image_dark: assets/images/app_icon_FA233B.png
  ios: true
