name: core
publish_to: "none"

version: 1.3.0

environment:
  sdk: 3.5.0-180.3.beta
  flutter: 3.23.0-0.1.pre

dependencies:
  adaptive_dialog: ^2.2.0
  budoux_dart: ^1.2.0
  clock: ^1.1.1
  cloud_firestore: ^5.1.0
  cloud_functions: ^5.0.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  feedback: ^3.1.0
  firebase_analytics: ^11.2.0
  firebase_app_check: ^0.3.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_performance: ^0.10.0+1
  firebase_remote_config: ^5.0.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.2.7
  google_mobile_ads: ^5.1.0
  hooks_riverpod: ^2.5.1
  in_app_review: ^2.0.9
  intersperse: ^2.0.0
  intl: any
  jovial_svg: ^1.1.22
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.2
  quick_actions: ^1.0.7
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  smooth_page_indicator: ^1.2.0+3
  talker: ^4.4.0
  talker_flutter: ^4.4.0
  talker_riverpod_logger: ^4.4.0
  url_launcher: ^6.3.0
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.9
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  slang_build_runner: ^3.31.0
  test: any
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/budoux_dart/models/ja.json

    - assets/si/apple-light.si
    - assets/si/apple-dark.si
    - assets/si/google-light.si
    - assets/si/google-dark.si
    - assets/si/github-light.si
    - assets/si/github-dark.si
