name: core
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.3.0-0"
  flutter: "^3.17.0-0"

dependencies:
  adaptive_dialog: ^2.0.0
  budoux_dart: ^1.1.0
  clock: ^1.1.1
  cloud_firestore: ^4.13.2
  cloud_functions: ^4.5.5
  collection: ^1.18.0
  device_info_plus: ^9.1.1
  firebase_analytics: ^10.7.1
  firebase_app_check: ^0.2.1+6
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.5
  firebase_dynamic_links: ^5.4.5
  firebase_performance: ^0.9.3+5
  firebase_remote_config: ^4.3.5
  firebase_ui_auth: ^1.10.0
  firebase_ui_oauth_apple: ^1.2.14
  firebase_ui_oauth_google: ^1.2.14
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^12.1.1
  hooks_riverpod: ^2.4.9
  intersperse: ^2.0.0
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  riverpod_annotation: ^2.3.3
  roggle: ^0.4.2+1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  test: ^1.24.9
  very_good_analysis: ^5.1.0
