name: core
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.0-0
  flutter: ^3.20.0-0

dependencies:
  adaptive_dialog: ^2.1.0
  budoux_dart: ^1.2.0
  clock: ^1.1.1
  cloud_firestore: ^4.15.8
  cloud_functions: ^4.6.8
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  feedback: ^3.0.1
  firebase_analytics: ^10.8.9
  firebase_app_check: ^0.2.1+13
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  firebase_dynamic_links: ^5.4.17
  firebase_performance: ^0.9.3+13
  firebase_remote_config: ^4.3.17
  firebase_ui_auth: ^1.13.1
  firebase_ui_localizations: ^1.10.2
  firebase_ui_oauth_apple: ^1.2.19
  firebase_ui_oauth_google: ^1.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.0
  google_mobile_ads: ^4.0.0
  hooks_riverpod: ^2.5.1
  in_app_review: ^2.0.8
  intersperse: ^2.0.0
  intl: any
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  quick_actions: ^1.0.7
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  simple_logger: ^1.9.0+3
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  slang_build_runner: ^3.30.0
  test: any
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

  assets:
    - packages/budoux_dart/models/ja.json
