name: obento
publish_to: "none"

version: 1.2.0

environment:
  sdk: 3.4.1
  flutter: 3.22.1

dependencies:
  adaptive_dialog: ^2.1.0
  cloud_firestore: ^4.17.5
  collection: ^1.18.0
  core:
    path: ../core
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.1.4
  hooks_riverpod: ^2.5.1
  intersperse: ^2.0.0
  intl: any
  jovial_svg: ^1.1.21
  media_query_preview: ^0.0.2
  pull_down_button: ^0.9.4
  riverpod_annotation: ^2.3.5
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.5.0+1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  slang_build_runner: ^3.31.0
  test: any
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - packages/budoux_dart/models/ja.json

    - assets/images/app_icon.webp

    - assets/images/onboarding/screenshot_0.webp
    - assets/images/onboarding/screenshot_1.webp
    - assets/images/onboarding/screenshot_2.webp
    - assets/images/onboarding/screenshot_3.webp
    - assets/images/onboarding/screenshot_4.webp
    - assets/images/onboarding/screenshot_5.webp
    - assets/images/onboarding/screenshot_6.webp
    - assets/images/onboarding/screenshot_7.webp
flutter_native_splash:
  color: "#FF9800"
  color_dark: "#FF5722"
  image: assets/images/app_icon_light.png
  image_dark: assets/images/app_icon_dark.png
  ios: true
  android: true
