name: obento
publish_to: "none"

version: 1.1.0

environment:
  sdk: ^3.4.0-0
  flutter: ^3.22.0-0

dependencies:
  adaptive_dialog: ^2.1.0
  budoux_dart: ^1.2.0
  clock: ^1.1.1
  cloud_firestore: ^4.17.3
  cloud_functions: ^4.7.4
  collection: ^1.18.0
  core:
    path: ../core
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  feedback: ^3.1.0
  firebase_analytics: ^10.10.5
  firebase_app_check: ^0.2.2+5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_performance: ^0.9.4+4
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.1.1
  hooks_riverpod: ^2.5.1
  in_app_review: ^2.0.9
  intersperse: ^2.0.0
  intl: any
  jovial_svg: ^1.1.21
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  pull_down_button: ^0.9.4
  quick_actions: ^1.0.7
  riverpod_annotation: ^2.3.5
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  smooth_page_indicator: ^1.1.0
  talker: ^4.2.0
  talker_flutter: ^4.2.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.6.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  slang_build_runner: ^3.30.0
  test: any
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - packages/budoux_dart/models/ja.json

    - assets/images/app_icon.webp

    - assets/images/onboarding/screenshot_0.webp
    - assets/images/onboarding/screenshot_1.webp
    - assets/images/onboarding/screenshot_2.webp
    - assets/images/onboarding/screenshot_3.webp
    - assets/images/onboarding/screenshot_4.webp
    - assets/images/onboarding/screenshot_5.webp
    - assets/images/onboarding/screenshot_6.webp
    - assets/images/onboarding/screenshot_7.webp
flutter_native_splash:
  color: "#FF9800"
  color_dark: "#FF5722"
  image: assets/images/app_icon_light.png
  image_dark: assets/images/app_icon_dark.png
  ios: true
  android: true
