name: actionlint

on:
  workflow_dispatch:
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: KoheiKanagu/composite-actions/run-actionlint@main
