name: Build and Publish Flutter Docker Image

on:
  workflow_dispatch:
    inputs:
      FLUTTER_VERSION:
        description: 'Flutter version'
        required: true
        default: '3.22.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: flutter

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-docker
  cancel-in-progress: true

jobs:
  build_and_publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.FLUTTER_VERSION }}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          build-args: |
            FLUTTER_VERSION=${{ inputs.FLUTTER_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1.1.2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
