name: Firebase Deploy Dev

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-Dev
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: # for KoheiKanagu/composite-actions/setup-firebase-cli@main
      id-token: write
      contents: read

    steps:
      ### Setup ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      - name: Setup Firebase CLI
        uses: KoheiKanagu/composite-actions/setup-firebase-cli@main
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.SERVICE_ACCOUNT_DEV }}

      - run: |
          firebase use dev --debug

      - name: Install dependencies
        run: npm ci
        working-directory: firebase/functions

      - name: Replace remoteconfig template conditions
        run: |
          dart pub get
          dart run grinder replace-remoteconfig-template-conditions

      - name: Export Firebase Admin SDK Service Account
        run: |
          # https://github.com/firebase/firebase-admin-node/issues/1377
          # Workaround for the issue above
          echo ${{ secrets.FIREBASE_ADMIN_SDK_SERVICE_ACCOUNT_DEV }} | base64 --decode > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/service-account.json

      ### Deploy ###
      - name: Deploy Mail Templates
        working-directory: firebase/functions
        run: |
          npx ts-node scripts/set_mail_templates.ts --force

      - name: Firebase Deploy
        run: |
          firebase deploy --force --except extensions

      ### Cleanup ###
      - name: Cleanup
        if: always()
        run: |
          rm -f service-account.json
