name: Firebase Deploy Prod

on:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-Prod
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: # for KoheiKanagu/composite-actions/setup-firebase-cli@main
      id-token: write
      contents: read

    steps:
      ### Setup ###
      - uses: actions/checkout@v4

      - name: Setup Firebase CLI
        uses: KoheiKanagu/composite-actions/setup-firebase-cli@main
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ vars.SERVICE_ACCOUNT_PROD }}

      - run: |
          firebase use prod --debug

      - name: Install dependencies
        run: npm ci
        working-directory: firebase/functions

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: dev

      - name: Replace remoteconfig template conditions
        run: |
          dart pub get
          grind replace-remoteconfig-template-conditions

      ### Deploy ###
      - name: Deploy
        run: |
          firebase deploy --force --except extensions
