name: Pull Request

on:
  workflow_dispatch:
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-pull_request
  cancel-in-progress: true

jobs:
  generate:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: # for KoheiKanagu/composite-actions/setup-firebase-cli@main
      id-token: write
      contents: read
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      - name: Setup Firebase CLI Dev
        uses: KoheiKanagu/composite-actions/setup-firebase-cli@main
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.SERVICE_ACCOUNT_DEV }}

      ### Generate ###
      - run: |
          melos run generate
          git diff --exit-code

  fix-format:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      ### fix and format ###
      - name: Fix and Format
        run: |
          melos run dart:fix:format
          git diff --exit-code

  analyze:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      ### Analyze ###
      - run: melos run dart:analyze

  custom_lint:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      ### Custom Lint ###
      - run: melos run dart:custom_lint

  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      ### Test ###
      - name: Test
        run: |
          melos run flutter:test --no-select

  golden_test:
    timeout-minutes: 30
    runs-on: macos-14
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      ### Test ###
      - name: Test
        run: |
          melos run flutter:golden:test --no-select

      - name: Upload a Build Artifact
        if: always()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: golden_failures
          path: packages/*/test/**/failures/

  pod_install:
    timeout-minutes: 60
    runs-on: macos-13
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      - name: Pods Cache
        uses: actions/cache@v4
        with:
          path: |
            packages/*/ios/Pods
            ~/Library/Caches/CocoaPods/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Update CocoaPods
        run: gem update cocoapods

      ### Build ###
      - run: melos run pub:get

      - run: melos run pod:install

      - run: git diff --exit-code

  firebase-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: # for KoheiKanagu/composite-actions/setup-firebase-cli@main
      id-token: write
      contents: read
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Firebase CLI Dev
        uses: KoheiKanagu/composite-actions/setup-firebase-cli@main
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.SERVICE_ACCOUNT_DEV }}

      ### Test ###
      - name: Test
        run: |
          ./firebase_emulators_test.sh
